[project]
name = "euler-rust"
version = "0.0.1"
authors =  ["Theodore Nordsieck"]

[[bin]]
name = "0001"

[[bin]]
name = "0002"

[[bin]]
name = "0003"

[[bin]]
name = "0004"

[[bin]]
name = "0005"

[[bin]]
name = "0006"